# Data Summarisation

From the cleaned data, a summary of each batter will be created in this document. The summaries of each batter include numerous features that have been chosen as contributing factors to a batters performance. The feature set is intentionally extensive - exploration into which features are most important follow this document. The summarised data produced in this document will  provided the basis for the modelling phase.

Summaries of each player include the following features:

1. Summarise batter attributes.<br>
    a. Handedness.<br>
    b. Name.<br>
2. Summarise One-Day International Batting Average.
3. Summarise matches played.<br>
    a. Number of domestic One-Day matches.<br>
    b. Number of domestic Test matches.<br>
    c. Number of domestic T20 matches.<br>
    d. Percentage of domestic One-Day matches.<br>
    e. Percentage of domestic Test matches.<br>
    f. Percentage of domestic T20 matches.<br>
    g. Number of domestic One-Day innings.<br>
    h. Number of domestic Test innings.<br>
    i. Number of domestic T20 innings.<br>
    j. Percentage of domestic One-Day innings.<br>
    k. Percentage of domestic Test innings.<br>
    l. Percentage of domestic T20 innings.<br>
    m. Percentage of domestic One-Day wins.<br>
    n. Percentage of domestic Test wins.<br>
    o. Percentage of domestic T20 wins.<br>
4. Summarise wickets.<br>
    a. Percentage of domestic One-Day not outs.<br>
    b. Percentage of domestic One-Day wickets bowled.<br>
    c. Percentage of domestic One-Day wickets caught.<br>
    d. Percentage of domestic One-Day wickets lbw.<br>
    e. Percentage of domestic One-Day wickets hit wicket.<br>
    f. Percentage of domestic One-Day wickets stumped.<br>
    g. Percentage of domestic One-Day wickets runout.<br>
    h. Percentage of domestic One-Day wickets hanlded ball.<br>
    i. Percentage of domestic One-Day wickets hit ball twice.<br>
    j. Percentage of domestic One-Day wickets obstructed field.<br>
    k. Percentage of domestic One-Day wickets timed out.<br>
    l. Percentage of domesticTest not outs.<br>
    m. Percentage of domestic Test wickets bowled.<br>
    n. Percentage of domestic Test wickets caught.<br>
    o. Percentage of domestic Test wickets lbw.<br>
    p. Percentage of domestic Test wickets hit wicket.<br>
    q. Percentage of domestic Test wickets stumped.<br>
    r. Percentage of domestic Test wickets runout.<br>
    s. Percentage of domestic Test wickets hanlded ball.<br>
    t. Percentage of domestic Test wickets hit ball twice.<br>
    u. Percentage of domestic Test wickets obstructed field.<br>
    v. Percentage of domestic Test wickets timed out.<br>
    w. Percentage of domestic T20 not outs.<br>
    x. Percentage of domestic T20 wickets bowled.<br>
    y. Percentage of domestic T20 wickets caught.<br>
    z. Percentage of domestic T20 wickets lbw.<br>
    aa. Percentage of domestic T20 wickets hit wicket.<br>
    ab. Percentage of domestic T20 wickets stumped.<br>
    ac. Percentage of domestic T20 wickets runout.<br>
    ad. Percentage of domestic T20 wickets hanlded ball.<br>
    ae. Percentage of domestic T20 wickets hit ball twice.<br>
    af. Percentage of domestic T20 wickets obstructed field.<br>
    ag. Percentage of domestic T20 wickets timed out.<br>
5. Summarise runs.<br>
    a. Percentage of domestic One-Day dot balls (no runs).<br>
    b. Percentage of domestic One-Day one-run balls (1 run).<br>
    c. Percentage of domestic One-Day two-run balls (2 runs).<br>
    d. Percentage of domestic One-Day three-run balls (3 runs).<br>
    e. Percentage of domestic One-Day four-run balls (4 runs).<br>
    f. Percentage of domestic One-Day five-run balls (5 runs).<br>
    g. Percentage of domestic One-Day six-run balls (6 runs).<br>
    h. Average runs per domestic One-Day match.<br>
    i. Average runs per domestic One-Day innings.<br>
    j. Domestic One-Day high score.<br>
    k. Percentage of domestic Test dot balls (no runs).<br>
    l. Percentage of domestic Test one-run balls (1 run).<br>
    m. Percentage of domestic Test two-run balls (2 runs).<br>
    n. Percentage of domestic Test three-run balls (3 runs).<br>
    o. Percentage of domestic Test four-run balls (4 runs).<br>
    p. Percentage of domestic Test five-run balls (5 runs).<br>
    q. Percentage of domestic Test six-run balls (6 runs).<br>
    r. Average runs per domestic Test match.<br>
    s. Average runs per domestic Test innings.<br>
    t. Domestic Test high score.<br>
    u. Percentage of domestic T20 dot balls (no runs).<br>
    v. Percentage of domestic T20 one-run balls (1 run).<br>
    w. Percentage of domestic T20 two-run balls (2 runs).<br>
    x. Percentage of domestic T20 three-run balls (3 runs).<br>
    y. Percentage of domestic T20 four-run balls (4 runs).<br>
    z. Percentage of domestic T20 five-run balls (5 runs).<br>
    aa. Percentage of domestic T20 six-run balls (6 runs).<br>
    ab. Average runs per domestic T20 match.<br>
    ac. Average runs per domestic T20 innings.<br>
    ad. Domestic T20 high score.<br>
6. Summarise milestones.<br>
    a. Percentage of domestic One-Day ducks.<br>
    b. Percentage of domestic One-Day starts.<br>
    c. Percentage of domestic One-Day 50s.<br>
    d. Percentage of domestic One-Day 100s.<br>
    e. Percentage of domestic One-Day 150s.<br>
    f. Percentage of domestic One-Day 200s.<br>
    g. Percentage of domestic One-Day 250s.<br>
    h. Percentage of domestic One-Day 300s.<br>
    i. Percentage of domestic Test ducks.<br>
    j. Percentage of domestic Test starts.<br>
    k. Percentage of domestic Test 50s.<br>
    l. Percentage of domestic Test 100s.<br>
    m. Percentage of domestic Test 150s.<br>
    n. Percentage of domestic Test 200s.<br>
    o. Percentage of domestic Test 250s.<br>
    p. Percentage of domestic Test 300s.<br>
    q. Percentage of domestic T20 ducks.<br>
    r. Percentage of domestic T20 starts.<br>
    s. Percentage of domestic T20 50s.<br>
    t. Percentage of domestic T20 100s.<br>
    u. Percentage of domestic T20 150s.<br>
    v. Percentage of domestic T20 200s.<br>
    w. Percentage of domestic T20 250s.<br>
    x. Percentage of domestic T20 300s.<br>
7. Summarise batting position.<br>
    a. The average number of balls that have been bowled when each batter faces their first ball in a domestic One-Day innings.<br>
    b. The average score when each batter faces their first ball in a domestic One-Day innings.<br>
    c. The average number of wickets fallen when each batter faces their first ball in a domestic One-Day innings.<br>
    d. The average number of balls that have been bowled when each batter faces their first ball in a domestic Test innings.<br>
    e. The average score when each batter faces their first ball in a domestic Test innings.<br>
    f. The average number of wickets fallen when each batter faces their first ball in a domestic Test innings.<br>
    g. The average number of balls that have been bowled when each batter faces their first ball in a domestic T20 innings.<br>
    h. The average score when each batter faces their first ball in a domestic T20 innings.<br>
    i. The average number of wickets fallen when each batter faces their first ball in a domestic T20 innings.<br>
8. Summarise batting style.<br>
    a. The average number of balls faced per innings in domestic One-Day matches.<br>
    b. The percentage of false shots performed by a batter in domestic One-Day matches.<br>
    c. The average strike rate of a batter in domestic One-Day matches.<br>
    d. The average number of balls faced per innings in domestic Test matches.<br>
    e. The percentage of false shots performed by a batter in domestic Test matches.<br>
    f. The average strike rate of a batter in domestic Test matches.<br>
    g. The average number of balls faced per innings in domestic T20 matches.<br>
    h. The percentage of false shots performed by a batter in domestic T20 matches.<br>
    i. The average strike rate of a batter in domestic T20 matches.<br>
9. Summarise team contribution.<br>
    a. The average percent of runs each batter contributes to their teams total in domestic One-Day matches.<br>
    b. How often each batter is the highest scorer of their team (%) in domestic One-Day matches.<br>
    c. The average percent of runs each batter contributes to their teams total in domestic Test matches.<br>
    d. How often each batter is the highest scorer of their team (%) in domestic Test matches.<br>
    e. The average percent of runs each batter contributes to their teams total in domestic T20 matches.<br>
    f. How often each batter is the highest scorer of their team (%) in domestic T20 matches.<br>

To begin with, we will perform the necessary imports and load the summary, delivery, and match datasets.

In [1]:
# Import necessary libraries.
import numpy as np
import pandas as pd
from lib.constants import DATA_PATH

# Load delivery and match data.
summary_data = pd.read_csv(DATA_PATH + "/Batter_Summary.txt", delimiter="\t")
delivery_data = pd.read_csv(
    DATA_PATH + "/Deliveries_Clean.txt", delimiter="\t", low_memory=False)
match_data = pd.read_csv(DATA_PATH + "/Matches_Clean.txt", delimiter="\t")

# Reset data for later joins.
delivery_data.rename(
    columns={"Striker Id": "Batter_ID", "Match Id": "Match_ID"}, inplace=True)
match_data.rename(columns={"Match Id": "Match_ID"}, inplace=True)

## 1. Summarise Batter Attributes.

Here, we will summarise each batters attributes. This includes the following properties:

1. Batter name.
2. Batter hand (e.g., left or right).

In [2]:
# Extract important batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Get batter IDs and names.
df = delivery_data[delivery_data["Batter_ID"].isin(
    batter_ids)][["Batter_ID", "Striker", "Striker Hand"]]
df.rename({"Striker": "Name", "Striker Hand": "Hand"}, axis=1, inplace=True)

# Drop duplicate data.
df = df.drop_duplicates(["Batter_ID"])

# Join data with summary table.
summary_data = pd.merge(left=summary_data, right=df,
                        on="Batter_ID", how="inner")
summary_data

    Batter_ID                 Name   Hand
0          21       Bichel, Andrew  Right
1          22       Bevan, Michael   Left
2          29          Harvey, Ian  Right
3          30      Hayden, Matthew   Left
4          32           Hogg, Brad   Left
..        ...                  ...    ...
57    2480058  Labuschagne, Marnus  Right
58    2960012      Stoinis, Marcus  Right
59    2960022     Handscomb, Peter  Right
60    3080014         Head, Travis   Left
61    3080018          Zampa, Adam  Right

[62 rows x 3 columns]

## 2. Summarise One-Day International Batting Average.

This section performs only a single summarisation - determining the batting average of each batter in the One-Day international format. This batting average is the attribute we wish to predict in the model we develop. Importantly, the batting average is the number of runs per out, not per innings.

In [3]:
# Extract batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Extract match IDs and match types for international games.
match_ids = match_data[(match_data["Series"].str.contains("International")) & (
    match_data["Match Type Id"] == 1)]["Match_ID"].tolist()

# Extract deliveries to relevant batters.
runs_df = delivery_data[
    (delivery_data["Batter_ID"].isin(batter_ids)) & (
        delivery_data["Match_ID"].isin(match_ids))
][["Batter_ID", "Match_ID", "Innings", "Bat Score"]]

# Count the total number of runs for wach batter in ODI.
runs_df = runs_df.groupby("Batter_ID", as_index=False)[
    "Bat Score"].sum().rename({"Bat Score": "Total_Runs"}, axis=1)

# Extract the wickets of relevant batters.
wickets_df = delivery_data[
    (delivery_data["Batter Out Id"].isin(batter_ids)) & (
        delivery_data["Match_ID"].isin(match_ids))
][["Batter_ID", "Match_ID", "Innings", "Batter Out Id"]]

# Count the total number of outs for each batter.
wickets_df = wickets_df.groupby("Batter Out Id", as_index=False).size().rename(
    {"Batter Out Id": "Batter_ID", "size": "Out_Count"}, axis=1)

# Determine the batting average of each batter.
df = pd.merge(left=runs_df, right=wickets_df, on="Batter_ID", how="outer")
df["Total_Runs"] = np.where(
    df["Out_Count"] < 1,
    df["Total_Runs"],
    df["Total_Runs"]/df["Out_Count"]
)
df.rename({"Total_Runs": "International_One_Day_Batting_Average"},
          axis=1, inplace=True)
df.drop(columns=["Out_Count"], inplace=True)

# Join data into summary.
summary_data = pd.merge(left=summary_data, right=df,
                        on="Batter_ID", how="left")
summary_data

,Batter_ID,Name,Hand,International_One_Day_Batting_Average
0,21,"Bichel, Andrew",Right,23.250000
1,22,"Bevan, Michael",Left,45.901961
2,29,"Harvey, Ian",Right,19.785714
3,30,"Hayden, Matthew",Left,45.138211
4,32,"Hogg, Brad",Left,21.485714
...,...,...,...,...
57,2480058,"Labuschagne, Marnus",Right,37.866667
58,2960012,"Stoinis, Marcus",Right,33.540541
59,2960022,"Handscomb, Peter",Right,30.375000
60,3080014,"Head, Travis",Left,34.173913
61,3080018,"Zampa, Adam",Right,9.380952

## 3. Summarise Matches Played.

In this section, we will summarise the matches played by each batter. This summarisation will include:

1. Number of domestic One-Day matches.
2. Number of domestic Test matches.
3. Number of domestic T20 matches.
4. Percentage of domestic One-Day matches.
5. Percentage of domestic Test matches.
6. Percentage of domestic T20 matches.
7. Number of domestic One-Day innings.
8. Number of domestic Test innings.
9. Number of domestic T20 innings.
10. Percentage of domestic One-Day innings.
11. Percentage of domestic Test innings.
12. Percentage of domestic T20 innings.
13. Percentage of domestic One-Day wins.
14. Percentage of domestic Test wins.
15. Percentage of domestic T20 wins.

In [4]:
# Extract batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Extract match IDs and match types for domestic games.
match_df = match_data[match_data["Series"].str.contains(
    "Domestic")][["Match_ID", "Match Type Id"]]

# Extract deliveries to relevant batters and add match details.
df = delivery_data[delivery_data["Batter_ID"].isin(
    batter_ids)][["Batter_ID", "Match_ID", "Team Batting ResultId", "Innings"]]
df = pd.merge(left=match_df, right=df, on="Match_ID")


# Function to summarise a players matches.
def summarise_matches(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels
  gamesLabel = "Domestic_{}_Match_Count".format(format_label)
  inningsLabel = "Domestic_{}_Innings_Count".format(format_label)
  winLabel = "Domestic_{}_Win_Rate".format(format_label)

  # Count the number of games and innings played.
  games_df = df.copy()
  games_df["Innings"] = (df["Match_ID"].astype(
      str) + df["Innings"].astype(str)).astype(int)
  games_df = games_df.groupby(["Batter_ID"], as_index=False).agg(
      {"Innings": "nunique", "Match_ID": "nunique"})
  games_df.rename(columns={"Match_ID": gamesLabel,
                  "Innings": inningsLabel}, inplace=True)

  # Count the number of wins.
  wins_df = df[df["Team Batting ResultId"].isin([1, 2, 3, 4, 5, 15])]
  wins_df = wins_df.groupby(["Batter_ID"], as_index=False).agg({
      "Match_ID": "nunique"})
  wins_df.rename(columns={"Match_ID": winLabel}, inplace=True)

  # Add wins to game dataframe and determine win-rate.
  games_df = pd.merge(left=games_df, right=wins_df, on="Batter_ID", how="left")
  games_df[winLabel].fillna(0, inplace=True)
  games_df[winLabel] = np.where(
      games_df[gamesLabel] < 1,
      games_df[gamesLabel],
      games_df[winLabel]/games_df[gamesLabel]
  )

  # Insert data into summary dataframe.
  summary = pd.merge(left=summary, right=games_df, on="Batter_ID", how="left")
  summary.fillna({gamesLabel: 0, inningsLabel: 0, winLabel: 0}, inplace=True)
  summary = summary.astype(
      {gamesLabel: int, inningsLabel: int, winLabel: float})

  return summary


# Function to summarise the percentage of each format played by a batter.
def summarise_formats(summary: pd.DataFrame):
  # Format labels.
  one_day_match_count_label = "Domestic_One_Day_Match_Count"
  one_day_match_percent_label = "Domestic_One_Day_Match_Percent"
  one_day_innings_count_label = "Domestic_One_Day_Innings_Count"
  one_day_innings_percent_label = "Domestic_One_Day_Innings_Percent"
  test_match_count_label = "Domestic_Test_Match_Count"
  test_match_percent_label = "Domestic_Test_Match_Percent"
  test_innings_count_label = "Domestic_Test_Innings_Count"
  test_innings_percent_label = "Domestic_Test_Innings_Percent"
  t20_match_count_label = "Domestic_T20_Match_Count"
  t20_match_percent_label = "Domestic_T20_Match_Percent"
  t20_innings_count_label = "Domestic_T20_Innings_Count"
  t20_innings_percent_label = "Domestic_T20_Innings_Percent"

  # Extract necessary information.
  matches = summary[[
      "Batter_ID",
      one_day_match_count_label,
      test_match_count_label,
      t20_match_count_label
  ]].rename({
      one_day_match_count_label: one_day_match_percent_label,
      test_match_count_label: test_match_percent_label,
      t20_match_count_label: t20_match_percent_label
  }, axis=1)
  innings = summary[[
      "Batter_ID",
      one_day_innings_count_label,
      test_innings_count_label,
      t20_innings_count_label
  ]].rename({
      one_day_innings_count_label: one_day_innings_percent_label,
      test_innings_count_label: test_innings_percent_label,
      t20_innings_count_label: t20_innings_percent_label
  }, axis=1)

  # Determine the total number of games and innings for each batter.
  matches["Total_Games"] = (
      matches[one_day_match_percent_label] +
      matches[test_match_percent_label] +
      matches[t20_match_percent_label]
  )
  innings["Total_Innings"] = (
      innings[one_day_innings_percent_label] +
      innings[test_innings_percent_label] +
      innings[t20_innings_percent_label]
  )

  # Determine percentages.
  matches[one_day_match_percent_label] = np.where(
      matches["Total_Games"] < 1,
      matches["Total_Games"],
      matches[one_day_match_percent_label]/matches["Total_Games"]
  )
  matches[test_match_percent_label] = np.where(
      matches["Total_Games"] < 1,
      matches["Total_Games"],
      matches[test_match_percent_label]/matches["Total_Games"]
  )
  matches[t20_match_percent_label] = np.where(
      matches["Total_Games"] < 1,
      matches["Total_Games"],
      matches[t20_match_percent_label]/matches["Total_Games"]
  )
  matches.drop(columns=["Total_Games"], inplace=True)

  innings[one_day_innings_percent_label] = np.where(
      innings["Total_Innings"] < 1,
      innings["Total_Innings"],
      innings[one_day_innings_percent_label]/innings["Total_Innings"]
  )
  innings[test_innings_percent_label] = np.where(
      innings["Total_Innings"] < 1,
      innings["Total_Innings"],
      innings[test_innings_percent_label]/innings["Total_Innings"]
  )
  innings[t20_innings_percent_label] = np.where(
      innings["Total_Innings"] < 1,
      innings["Total_Innings"],
      innings[t20_innings_percent_label]/innings["Total_Innings"]
  )
  innings.drop(columns=["Total_Innings"], inplace=True)

  # Merge data into summary.
  summary = pd.merge(left=summary, right=matches, on="Batter_ID", how="left")
  summary = pd.merge(left=summary, right=innings, on="Batter_ID", how="left")
  return summary


# Summarise One-Day
games_df = df[df["Match Type Id"] == 1]
summary_data = summarise_matches(games_df, summary_data, "One_Day")

# Summarise Test
games_df = df[df["Match Type Id"].isin([4, 5])]
summary_data = summarise_matches(games_df, summary_data, "Test")

# Summarise T20
games_df = df[df["Match Type Id"] == 7]
summary_data = summarise_matches(games_df, summary_data, "T20")

# Summarise the percentage of each format played by a batter
summary_data = summarise_formats(summary_data)

summary_data

,Batter_ID,Name,Hand,International_One_Day_Batting_Average,Domestic_One_Day_Innings_Count,Domestic_One_Day_Match_Count,Domestic_One_Day_Win_Rate,Domestic_Test_Innings_Count,Domestic_Test_Match_Count,Domestic_Test_Win_Rate,Domestic_T20_Innings_Count,Domestic_T20_Match_Count,Domestic_T20_Win_Rate,Domestic_One_Day_Match_Percent,Domestic_Test_Match_Percent,Domestic_T20_Match_Percent,Domestic_One_Day_Innings_Percent,Domestic_Test_Innings_Percent,Domestic_T20_Innings_Percent
0,21,"Bichel, Andrew",Right,23.250000,26,26,0.500000,54,33,0.515152,4,4,0.250000,0.412698,0.523810,0.063492,0.309524,0.642857,0.047619
1,22,"Bevan, Michael",Left,45.901961,20,20,0.450000,43,24,0.291667,0,0,0.000000,0.454545,0.545455,0.000000,0.317460,0.682540,0.000000
2,29,"Harvey, Ian",Right,19.785714,10,10,0.400000,22,13,0.538462,0,0,0.000000,0.434783,0.565217,0.000000,0.312500,0.687500,0.000000
3,30,"Hayden, Matthew",Left,45.138211,8,8,0.375000,12,7,0.714286,7,7,0.428571,0.363636,0.318182,0.318182,0.296296,0.444444,0.259259
4,32,"Hogg, Brad",Left,21.485714,15,15,0.266667,18,12,0.333333,15,15,0.200000,0.357143,0.285714,0.357143,0.312500,0.375000,0.312500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2480058,"Labuschagne, Marnus",Right,37.866667,26,26,0.615385,98,54,0.462963,15,15,0.400000,0.273684,0.568421,0.157895,0.187050,0.705036,0.107914
58,2960012,"Stoinis, Marcus",Right,33.540541,38,38,0.500000,95,52,0.403846,71,71,0.507042,0.236025,0.322981,0.440994,0.186275,0.465686,0.348039
59,2960022,"Handscomb, Peter",Right,30.375000,58,58,0.431034,123,73,0.410959,57,57,0.578947,0.308511,0.388298,0.303191,0.243697,0.516807,0.239496
60,3080014,"Head, Travis",Left,34.173913,27,27,0.296296,149,79,0.253165,48,48,0.625000,0.175325,0.512987,0.311688,0.120536,0.665179,0.214286
61,3080018,"Zampa, Adam",Right,9.380952,29,29,0.275862,61,34,0.205882,29,29,0.206897,0.315217,0.369565,0.315217,0.243697,0.512605,0.243697

## 4. Summarise Wickets.

Here, we summarise the wickets of each batter, including:

1. Percentage of domestic One-Day not outs.
2. Percentage of domestic One-Day wickets bowled.
3. Percentage of domestic One-Day wickets caught.
4. Percentage of domestic One-Day wickets lbw.
5. Percentage of domestic One-Day wickets hit wicket.
6. Percentage of domestic One-Day wickets stumped.
7. Percentage of domestic One-Day wickets runout.
8. Percentage of domestic One-Day wickets hanlded ball.
9. Percentage of domestic One-Day wickets hit ball twice.
10. Percentage of domestic One-Day wickets obstructed field.
11. Percentage of domestic One-Day wickets timed out.
12. Percentage of domesticTest not outs.
13. Percentage of domestic Test wickets bowled.
14. Percentage of domestic Test wickets caught.
15. Percentage of domestic Test wickets lbw.
16. Percentage of domestic Test wickets hit wicket.
17. Percentage of domestic Test wickets stumped.
18. Percentage of domestic Test wickets runout.
19. Percentage of domestic Test wickets hanlded ball.
20. Percentage of domestic Test wickets hit ball twice.
21. Percentage of domestic Test wickets obstructed field.
22. Percentage of domestic Test wickets timed out.
23. Percentage of domestic T20 not outs.
24. Percentage of domestic T20 wickets bowled.
25. Percentage of domestic T20 wickets caught.
26. Percentage of domestic T20 wickets lbw.
27. Percentage of domestic T20 wickets hit wicket.
28. Percentage of domestic T20 wickets stumped.
29. Percentage of domestic T20 wickets runout.
30. Percentage of domestic T20 wickets hanlded ball.
31. Percentage of domestic T20 wickets hit ball twice.
32. Percentage of domestic T20 wickets obstructed field.
33. Percentage of domestic T20 wickets timed out.

In [5]:
# Extract batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Extract match IDs and match types for domestic games.
match_df = match_data[match_data["Series"].str.contains(
    "Domestic")][["Match_ID", "Match Type Id"]]

# Extract deliveries to relevant batters and add match details.
df = delivery_data[(delivery_data["Batter Out Id"].isin(batter_ids)) & (
    ~delivery_data["How Out"].isna())][["Batter Out Id", "Match_ID", "Innings", "How Out"]]
df.rename({"Batter Out Id": "Batter_ID"}, axis=1, inplace=True)
df = pd.merge(left=match_df, right=df, on="Match_ID")


# Function to summarise each batters wickets.
def summarise_wickets(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels
  not_out_label = "Domestic_{}_Not_Out_Percent".format(format_label)
  bowled_label = "Domestic_{}_Bowled_Percent".format(format_label)
  caught_label = "Domestic_{}_Caught_Percent".format(format_label)
  lbw_label = "Domestic_{}_LBW_Percent".format(format_label)
  hit_wicket_label = "Domestic_{}_Hit_Wicket_Percent".format(format_label)
  stumped_label = "Domestic_{}_Stumped_Percent".format(format_label)
  run_out_label = "Domestic_{}_Run_Out_Percent".format(format_label)
  handled_ball_label = "Domestic_{}_Handled_Ball_Percent".format(format_label)
  hit_ball_twice_label = "Domestic_{}_Hit_Ball_Twice_Percent".format(
      format_label)
  obstructed_field_label = "Domestic_{}_Obstructed_Field_Percent".format(
      format_label)
  timed_out_label = "Domestic_{}_Timed_Out_Percent".format(format_label)

  innings_label = "Domestic_{}_Innings_Count".format(format_label)

  # Determine how often a batter gets out in each way.
  how_out = df.groupby(["Batter_ID", "How Out"]).size(
  ).reset_index().rename({0: "Out_Percent"}, axis=1)
  how_out = pd.merge(left=summary[["Batter_ID", innings_label]],
                     right=how_out, on="Batter_ID", how="left")

  # Determine how often a batter is not out.
  not_out = how_out.groupby(
      "Batter_ID", as_index=False).agg({"Out_Percent": "sum"})
  not_out = pd.merge(left=summary[["Batter_ID", innings_label]],
                     right=not_out, on="Batter_ID", how="left")
  not_out["Out_Percent"] = np.where(
      not_out[innings_label] < 1,
      not_out[innings_label],
      not_out[innings_label] - not_out["Out_Percent"]
  )
  not_out = not_out[not_out["Out_Percent"] > 0]
  not_out["How Out"] = "NO"
  how_out = how_out.append(not_out, ignore_index=True)

  # Determine percentage of each wicket occurring.
  how_out["Out_Percent"] = np.where(
      how_out[innings_label] < 1,
      how_out[innings_label],
      how_out["Out_Percent"]/how_out[innings_label]
  )
  how_out = how_out[["Batter_ID", "How Out", "Out_Percent"]]

  # Extract the percentage of each wicket occurrence.
  not_out = how_out.loc[how_out["How Out"] == "NO", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": not_out_label}, axis=1)
  bowled = how_out.loc[how_out["How Out"] == "B", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": bowled_label}, axis=1)
  caught = how_out.loc[how_out["How Out"] == "C", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": caught_label}, axis=1)
  lbw = how_out.loc[how_out["How Out"] == "LB", ["Batter_ID",
                                                 "Out_Percent"]].rename({"Out_Percent": lbw_label}, axis=1)
  hit_wicket = how_out.loc[how_out["How Out"] == "HW", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": hit_wicket_label}, axis=1)
  stumped = how_out.loc[how_out["How Out"] == "S", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": stumped_label}, axis=1)
  run_out = how_out.loc[how_out["How Out"] == "RO", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": run_out_label}, axis=1)
  handled_ball = how_out.loc[how_out["How Out"] == "HB", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": handled_ball_label}, axis=1)
  hit_ball_twice = how_out.loc[how_out["How Out"] == "HT", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": hit_ball_twice_label}, axis=1)
  obstructed_field = how_out.loc[how_out["How Out"] == "OF", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": obstructed_field_label}, axis=1)
  timed_out = how_out.loc[how_out["How Out"] == "TO", [
      "Batter_ID", "Out_Percent"]].rename({"Out_Percent": timed_out_label}, axis=1)

  # Merge all occurrences into a single dataframe.
  s = not_out
  s = pd.merge(left=s, right=bowled, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=caught, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=lbw, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=hit_wicket, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=stumped, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=run_out, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=handled_ball, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=hit_ball_twice, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=obstructed_field, on="Batter_ID", how="outer")
  s = pd.merge(left=s, right=timed_out, on="Batter_ID", how="outer")

  # Remove all NaNs.
  s.fillna({
      not_out_label: 0, bowled_label: 0, caught_label: 0, lbw_label: 0, hit_wicket_label: 0, stumped_label: 0,
      run_out_label: 0, handled_ball_label: 0, hit_ball_twice_label: 0, obstructed_field_label: 0, timed_out_label: 0
  }, inplace=True
  )

  # Merge wicket percentages into summary data
  summary = pd.merge(left=summary, right=s, on="Batter_ID", how="left")
  return summary


# Summarise One-Day wickets.
games_df = df[df["Match Type Id"] == 1]
summary_data = summarise_wickets(games_df, summary_data, "One_Day")

# Summarise Test wickets.
games_df = df[df["Match Type Id"].isin([4, 5])]
summary_data = summarise_wickets(games_df, summary_data, "Test")

# Summarise T20 wickets.
games_df = df[df["Match Type Id"] == 7]
summary_data = summarise_wickets(games_df, summary_data, "T20")
summary_data

,Batter_ID,Name,Hand,International_One_Day_Batting_Average,Domestic_One_Day_Innings_Count,Domestic_One_Day_Match_Count,Domestic_One_Day_Win_Rate,Domestic_Test_Innings_Count,Domestic_Test_Match_Count,Domestic_Test_Win_Rate,...,Domestic_T20_Bowled_Percent,Domestic_T20_Caught_Percent,Domestic_T20_LBW_Percent,Domestic_T20_Hit_Wicket_Percent,Domestic_T20_Stumped_Percent,Domestic_T20_Run_Out_Percent,Domestic_T20_Handled_Ball_Percent,Domestic_T20_Hit_Ball_Twice_Percent,Domestic_T20_Obstructed_Field_Percent,Domestic_T20_Timed_Out_Percent
0,21,"Bichel, Andrew",Right,23.250000,26,26,0.500000,54,33,0.515152,...,0.750000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
1,22,"Bevan, Michael",Left,45.901961,20,20,0.450000,43,24,0.291667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29,"Harvey, Ian",Right,19.785714,10,10,0.400000,22,13,0.538462,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,30,"Hayden, Matthew",Left,45.138211,8,8,0.375000,12,7,0.714286,...,0.142857,0.714286,0.000000,0.0,0.142857,0.000000,0.0,0.0,0.0,0.0
4,32,"Hogg, Brad",Left,21.485714,15,15,0.266667,18,12,0.333333,...,0.133333,0.200000,0.000000,0.0,0.000000,0.200000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2480058,"Labuschagne, Marnus",Right,37.866667,26,26,0.615385,98,54,0.462963,...,0.133333,0.600000,0.066667,0.0,0.000000,0.133333,0.0,0.0,0.0,0.0
58,2960012,"Stoinis, Marcus",Right,33.540541,38,38,0.500000,95,52,0.403846,...,0.098592,0.605634,0.070423,0.0,0.000000,0.042254,0.0,0.0,0.0,0.0
59,2960022,"Handscomb, Peter",Right,30.375000,58,58,0.431034,123,73,0.410959,...,0.105263,0.403509,0.035088,0.0,0.070175,0.105263,0.0,0.0,0.0,0.0
60,3080014,"Head, Travis",Left,34.173913,27,27,0.296296,149,79,0.253165,...,0.187500,0.625000,0.020833,0.0,0.041667,0.020833,0.0,0.0,0.0,0.0
61,3080018,"Zampa, Adam",Right,9.380952,29,29,0.275862,61,34,0.205882,...,0.241379,0.310345,0.000000,0.0,0.034483,0.103448,0.0,0.0,0.0,0.0

## 5. Summarise Runs.

In this section, we summarise the runs score by each batter. This includes the following attributes:

1. Percentage of domestic One-Day dot balls (no runs).
2. Percentage of domestic One-Day one-run balls (1 run).
3. Percentage of domestic One-Day two-run balls (2 runs).
4. Percentage of domestic One-Day three-run balls (3 runs).
5. Percentage of domestic One-Day four-run balls (4 runs).
6. Percentage of domestic One-Day five-run balls (5 runs).
7. Percentage of domestic One-Day six-run balls (6 runs).
8. Average runs per domestic One-Day match.
9. Average runs per domestic One-Day innings.
10. Domestic One-Day high score.
11. Percentage of domestic Test dot balls (no runs).
12. Percentage of domestic Test one-run balls (1 run).
13. Percentage of domestic Test two-run balls (2 runs).
14. Percentage of domestic Test three-run balls (3 runs).
15. Percentage of domestic Test four-run balls (4 runs).
16. Percentage of domestic Test five-run balls (5 runs).
17. Percentage of domestic Test six-run balls (6 runs).
18. Average runs per domestic Test match.
19. Average runs per domestic Test innings.
20. Domestic Test high score.
21. Percentage of domestic T20 dot balls (no runs).
22. Percentage of domestic T20 one-run balls (1 run).
23. Percentage of domestic T20 two-run balls (2 runs).
24. Percentage of domestic T20 three-run balls (3 runs).
25. Percentage of domestic T20 four-run balls (4 runs).
26. Percentage of domestic T20 five-run balls (5 runs).
27. Percentage of domestic T20 six-run balls (6 runs).
28. Average runs per domestic T20 match.
29. Average runs per domestic T20 innings.
30. Domestic T20 high score.

In [6]:
# Extract batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Extract match IDs and match types for domestic games.
match_df = match_data[match_data["Series"].str.contains(
    "Domestic")][["Match_ID", "Match Type Id"]]

# Extract deliveries to relevant batters and add match details.
df1 = delivery_data[delivery_data["Batter_ID"].isin(
    batter_ids)][["Batter_ID", "Match_ID", "Innings", "Bat Score"]]
df1 = pd.merge(left=match_df, right=df1, on="Match_ID")

df2 = delivery_data[delivery_data["Batter Out Id"].isin(
    batter_ids)][["Batter Out Id", "Match_ID", "Innings", "How Out"]]
df2 = pd.merge(left=match_df, right=df2, on="Match_ID")


# Function to summarise the spread of runs for each batter (e.g., % of dots, 1s, 2s,...).
def summarise_run_spread(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels.
  dot_label = "Domestic_{}_Dot_Rate".format(format_label)
  one_label = "Domestic_{}_One_Rate".format(format_label)
  two_label = "Domestic_{}_Two_Rate".format(format_label)
  three_label = "Domestic_{}_Three_Rate".format(format_label)
  four_label = "Domestic_{}_Four_Rate".format(format_label)
  five_label = "Domestic_{}_Five_Rate".format(format_label)
  six_label = "Domestic_{}_Six_Rate".format(format_label)

  # Extract run and ball count for each batter.
  runs = df[["Batter_ID", "Bat Score"]].groupby(
      ["Batter_ID", "Bat Score"], as_index=False).size()
  runs = runs.rename({"size": "Count"}, axis=1)
  balls = df[["Batter_ID", "Bat Score"]].groupby(
      "Batter_ID", as_index=False).size()
  balls = balls.rename({"size": "Balls"}, axis=1)

  # Determine rate of occurrence of each run type.
  runs = pd.merge(left=runs, right=balls, on="Batter_ID", how="left")
  runs["Count"] = np.where(
      runs["Balls"] < 1,
      runs["Balls"],
      runs["Count"]/runs["Balls"]
  )

  # Extract run rates into individual dataframes.
  dots = runs[runs["Bat Score"] == 0][["Batter_ID", "Count"]].rename(
      {"Count": dot_label}, axis=1)
  ones = runs[runs["Bat Score"] == 1][["Batter_ID", "Count"]].rename(
      {"Count": one_label}, axis=1)
  twos = runs[runs["Bat Score"] == 2][["Batter_ID", "Count"]].rename(
      {"Count": two_label}, axis=1)
  threes = runs[runs["Bat Score"] == 3][["Batter_ID", "Count"]].rename(
      {"Count": three_label}, axis=1)
  fours = runs[runs["Bat Score"] == 4][["Batter_ID", "Count"]].rename(
      {"Count": four_label}, axis=1)
  fives = runs[runs["Bat Score"] == 5][["Batter_ID", "Count"]].rename(
      {"Count": five_label}, axis=1)
  sixes = runs[runs["Bat Score"] == 6][["Batter_ID", "Count"]].rename(
      {"Count": six_label}, axis=1)

  # Combine run rates into single dataframe.
  s = dots
  s = pd.merge(left=s, right=ones, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=twos, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=threes, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=fours, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=fives, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=sixes, on="Batter_ID", how="left")

  # Fill empty values (e.q., when someone has not scored a particular run).
  s.fillna({
      dot_label: 0, one_label: 0, two_label: 0, three_label: 0,
      four_label: 0, five_label: 0, six_label: 0
  }, inplace=True
  )

  # Merge rates into the summary.
  summary = pd.merge(left=summary, right=s, on="Batter_ID", how="left")
  return summary


# Function to summarise the averages of each batter.
def summarise_average(df1: pd.DataFrame, df2: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels
  runs_per_innings_label = "Domestic_{}_Runs_Per_Innings_Average".format(
      format_label)
  runs_per_out_label = "Domestic_{}_Runs_Per_Out_Average".format(format_label)
  innings_label = "Domestic_{}_Innings_Count".format(format_label)
  outs_label = "Domestic_{}_Out_Count".format(format_label)

  # Extract number of runs for each batter.
  runs = df1[["Batter_ID", "Bat Score"]]
  runs = runs.groupby(["Batter_ID"], as_index=False).sum()

  # Extract number of outs for each batter.
  outs = df2[~df2["How Out"].isna()]["Batter Out Id"].to_frame().rename({
      "Batter Out Id": "Batter_ID"}, axis=1)
  outs = outs.groupby("Batter_ID", as_index=False).size().rename(
      {"size": outs_label}, axis=1)

  # Extract number of innings for each batter.
  innings = summary[["Batter_ID", innings_label]]

  # Merge innings and outs into runs dataframe.
  runs = pd.merge(left=runs, right=innings, on="Batter_ID", how="left")
  runs = pd.merge(left=runs, right=outs, on="Batter_ID", how="left")

  # Determine batting averages.
  runs[runs_per_innings_label] = np.where(
      runs[innings_label] < 1,
      runs["Bat Score"],
      runs["Bat Score"]/runs[innings_label]
  )
  runs[runs_per_out_label] = np.where(
      runs[outs_label] < 1,
      runs["Bat Score"],
      runs["Bat Score"]/runs[outs_label]
  )
  runs = runs[["Batter_ID", runs_per_innings_label, runs_per_out_label]]

  # Merge averages into summary.
  summary = pd.merge(left=summary, right=runs, on="Batter_ID", how="left")
  return summary


# Function to summarise the high score for each batter.
def summarise_high_score(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format label
  high_score_label = "Domestic_{}_High_Score".format(format_label)

  # Determine high score for each batter.
  df = df[["Batter_ID", "Match_ID", "Innings", "Bat Score"]]
  df = df.groupby(["Batter_ID", "Match_ID", "Innings"], as_index=False).sum()
  df = df.groupby(["Batter_ID"], as_index=False)["Bat Score"].max().rename(
      {"Bat Score": high_score_label}, axis=1)

  # Add high score to summary.
  summary = pd.merge(left=summary, right=df, on="Batter_ID", how="left")
  return summary


# Summarise One-Day runs.
games_df1 = df1[df1["Match Type Id"] == 1]
games_df2 = df2[df2["Match Type Id"] == 1]
summary_data = summarise_run_spread(games_df1, summary_data, "One_Day")
summary_data = summarise_average(games_df1, games_df2, summary_data, "One_Day")
summary_data = summarise_high_score(games_df1, summary_data, "One_Day")

# Summarise Test runs.
games_df1 = df1[df1["Match Type Id"].isin([4, 5])]
games_df2 = df2[df2["Match Type Id"].isin([4, 5])]
summary_data = summarise_run_spread(games_df1, summary_data, "Test")
summary_data = summarise_average(games_df1, games_df2, summary_data, "Test")
summary_data = summarise_high_score(games_df1, summary_data, "Test")

# Summarise T20 runs.
games_df1 = df1[df1["Match Type Id"] == 7]
games_df2 = df2[df2["Match Type Id"] == 7]
summary_data = summarise_run_spread(games_df1, summary_data, "T20")
summary_data = summarise_average(games_df1, games_df2, summary_data, "T20")
summary_data = summarise_high_score(games_df1, summary_data, "T20")
summary_data

,Batter_ID,Name,Hand,International_One_Day_Batting_Average,Domestic_One_Day_Innings_Count,Domestic_One_Day_Match_Count,Domestic_One_Day_Win_Rate,Domestic_Test_Innings_Count,Domestic_Test_Match_Count,Domestic_Test_Win_Rate,...,Domestic_T20_Dot_Rate,Domestic_T20_One_Rate,Domestic_T20_Two_Rate,Domestic_T20_Three_Rate,Domestic_T20_Four_Rate,Domestic_T20_Five_Rate,Domestic_T20_Six_Rate,Domestic_T20_Runs_Per_Innings_Average,Domestic_T20_Runs_Per_Out_Average,Domestic_T20_High_Score
0,21,"Bichel, Andrew",Right,23.250000,26,26,0.500000,54,33,0.515152,...,0.315789,0.315789,0.131579,0.000000,0.105263,0.0,0.131579,17.000000,22.666667,33.0
1,22,"Bevan, Michael",Left,45.901961,20,20,0.450000,43,24,0.291667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29,"Harvey, Ian",Right,19.785714,10,10,0.400000,22,13,0.538462,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,30,"Hayden, Matthew",Left,45.138211,8,8,0.375000,12,7,0.714286,...,0.415094,0.301887,0.094340,0.012579,0.138365,0.0,0.037736,29.714286,29.714286,77.0
4,32,"Hogg, Brad",Left,21.485714,15,15,0.266667,18,12,0.333333,...,0.439394,0.424242,0.060606,0.000000,0.030303,0.0,0.045455,4.133333,7.750000,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2480058,"Labuschagne, Marnus",Right,37.866667,26,26,0.615385,98,54,0.462963,...,0.320988,0.465021,0.115226,0.008230,0.069959,0.0,0.020576,18.200000,19.500000,49.0
58,2960012,"Stoinis, Marcus",Right,33.540541,38,38,0.500000,95,52,0.403846,...,0.386691,0.351319,0.097122,0.007794,0.115108,0.0,0.041966,30.098592,36.844828,147.0
59,2960022,"Handscomb, Peter",Right,30.375000,58,58,0.431034,123,73,0.410959,...,0.345183,0.431193,0.090596,0.006881,0.097477,0.0,0.028670,18.280702,25.414634,103.0
60,3080014,"Head, Travis",Left,34.173913,27,27,0.296296,149,79,0.253165,...,0.365591,0.381232,0.091887,0.008798,0.093842,0.0,0.058651,28.104167,31.372093,101.0
61,3080018,"Zampa, Adam",Right,9.380952,29,29,0.275862,61,34,0.205882,...,0.518987,0.310127,0.063291,0.012658,0.075949,0.0,0.018987,4.862069,7.050000,23.0

## 6. Summarise Milestones

Here, we summarise the milestones achieved by each batter. In general, milestones in cricket are recorded at every 50 runs, however, we have also included the occurrence of "ducks" (0 runs) and "starts" (1-49 runs) in the summary. Importantly, the milestones are determined based on the last ball a batter faces in an innings. This means that whether a batter gets out while on 0 runs, or the innings concludes while a batter is on 0 runs, both would be recorded as a duck. The following attributes have been recorded:

1. Percentage of domestic One-Day ducks.
2. Percentage of domestic One-Day starts.
3. Percentage of domestic One-Day 50s.
4. Percentage of domestic One-Day 100s.
5. Percentage of domestic One-Day 150s.
6. Percentage of domestic One-Day 200s.
7. Percentage of domestic One-Day 250s.
8. Percentage of domestic One-Day 300s.
9. Percentage of domestic Test ducks.
10. Percentage of domestic Test starts.
11. Percentage of domestic Test 50s.
12. Percentage of domestic Test 100s.
13. Percentage of domestic Test 150s.
14. Percentage of domestic Test 200s.
15. Percentage of domestic Test 250s.
16. Percentage of domestic Test 300s.
17. Percentage of domestic T20 ducks.
18. Percentage of domestic T20 starts.
19. Percentage of domestic T20 50s.
20. Percentage of domestic T20 100s.
21. Percentage of domestic T20 150s.
22. Percentage of domestic T20 200s.
23. Percentage of domestic T20 250s.
24. Percentage of domestic T20 300s.

In [7]:
# Extract batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Extract match IDs and match types for domestic games.
match_df = match_data[match_data["Series"].str.contains(
    "Domestic")][["Match_ID", "Match Type Id"]]

# Extract deliveries to relevant batters and add match details.
df = delivery_data[(delivery_data["Batter_ID"].isin(batter_ids))][[
    "Batter_ID", "Match_ID", "Innings", "Bat Score"]]
df = pd.merge(left=match_df, right=df, on="Match_ID")


# Function to summarise milestones.
def summarise_milestones(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels.
  duck_label = "Domestic_{}_Duck_Rate".format(format_label)
  start_label = "Domestic_{}_Start_Rate".format(format_label)
  fifty_label = "Domestic_{}_50_Rate".format(format_label)
  hundred_label = "Domestic_{}_100_Rate".format(format_label)
  onefifty_label = "Domestic_{}_150_Rate".format(format_label)
  twohundred_label = "Domestic_{}_200_Rate".format(format_label)
  twofifty_label = "Domestic_{}_250_Rate".format(format_label)
  threehundred_label = "Domestic_{}_300_Rate".format(format_label)
  innings_label = "Domestic_{}_Innings_Count".format(format_label)

  # Determine runs per game.
  df = df.groupby(["Batter_ID", "Match_ID", "Innings"], as_index=False).sum()

  # Extract different milestones.
  ducks = df[df["Bat Score"] == 0].groupby(
      "Batter_ID", as_index=False).size().rename({"size": duck_label}, axis=1)
  starts = df[(df["Bat Score"] >= 1) & (df["Bat Score"] < 50)].groupby(
      "Batter_ID", as_index=False).size().rename({"size": start_label}, axis=1)
  fifties = df[(df["Bat Score"] >= 50) & (df["Bat Score"] < 100)].groupby(
      "Batter_ID", as_index=False).size().rename({"size": fifty_label}, axis=1)
  hundreds = df[(df["Bat Score"] >= 100) & (df["Bat Score"] < 150)].groupby(
      "Batter_ID", as_index=False).size().rename({"size": hundred_label}, axis=1)
  onefifties = df[(df["Bat Score"] >= 150) & (df["Bat Score"] < 200)].groupby(
      "Batter_ID", as_index=False).size().rename({"size": onefifty_label}, axis=1)
  twohundreds = df[(df["Bat Score"] >= 200) & (df["Bat Score"] < 250)].groupby(
      "Batter_ID", as_index=False).size().rename({"size": twohundred_label}, axis=1)
  twofifties = df[(df["Bat Score"] >= 250) & (df["Bat Score"] < 300)].groupby(
      "Batter_ID", as_index=False).size().rename({"size": twofifty_label}, axis=1)
  threehundreds = df[(df["Bat Score"] >= 300) & (df["Bat Score"] < 350)].groupby(
      "Batter_ID", as_index=False).size().rename({"size": threehundred_label}, axis=1)

  # Merge milestones into a single dataframe.
  s = summary["Batter_ID"].to_frame()
  s = pd.merge(left=s, right=ducks, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=starts, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=fifties, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=hundreds, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=onefifties, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=twohundreds, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=twofifties, on="Batter_ID", how="left")
  s = pd.merge(left=s, right=threehundreds, on="Batter_ID", how="left")

  # Fill NaN fields.
  s.fillna({
      duck_label: 0, start_label: 0, fifty_label: 0, hundred_label: 0, onefifty_label: 0,
      twohundred_label: 0, twofifty_label: 0, threehundred_label: 0
  }, inplace=True
  )

  # Convert each milestone to a percentage.
  innings = summary[summary[innings_label] != 0][["Batter_ID", innings_label]]
  s = pd.merge(left=s, right=innings, on="Batter_ID", how="left")
  s[duck_label] = np.where(
      s[innings_label] < 1, s[innings_label], s[duck_label]/s[innings_label]
  )
  s[start_label] = np.where(
      s[innings_label] < 1, s[innings_label], s[start_label]/s[innings_label]
  )
  s[fifty_label] = np.where(
      s[innings_label] < 1, s[innings_label], s[fifty_label]/s[innings_label]
  )
  s[hundred_label] = np.where(
      s[innings_label] < 1, s[innings_label], s[hundred_label]/s[innings_label]
  )
  s[onefifty_label] = np.where(
      s[innings_label] < 1, s[innings_label], s[onefifty_label]/s[innings_label]
  )
  s[twohundred_label] = np.where(
      s[innings_label] < 1, s[innings_label], s[twohundred_label]/s[innings_label]
  )
  s[twofifty_label] = np.where(
      s[innings_label] < 1, s[innings_label], s[twofifty_label]/s[innings_label]
  )
  s[threehundred_label] = np.where(
      s[innings_label] < 1, s[innings_label], s[threehundred_label]/s[innings_label]
  )

  # Drop unnecessary columns.
  s.drop(columns=[innings_label], inplace=True)

  # Merge milestones into summary dataframe.
  summary = pd.merge(left=summary, right=s, on="Batter_ID", how="left")

  return summary


# Summarise One-Day milestones.
games_df = df[df["Match Type Id"] == 1][[
    "Batter_ID", "Match_ID", "Innings", "Bat Score"]]
summary_data = summarise_milestones(games_df, summary_data, "One_Day")

# Summarise Test milestones.
games_df = df[df["Match Type Id"].isin(
    [4, 5])][["Batter_ID", "Match_ID", "Innings", "Bat Score"]]
summary_data = summarise_milestones(games_df, summary_data, "Test")

# Summarise T20 milestones.
games_df = df[df["Match Type Id"] == 7][[
    "Batter_ID", "Match_ID", "Innings", "Bat Score"]]
summary_data = summarise_milestones(games_df, summary_data, "T20")
summary_data

,Batter_ID,Name,Hand,International_One_Day_Batting_Average,Domestic_One_Day_Innings_Count,Domestic_One_Day_Match_Count,Domestic_One_Day_Win_Rate,Domestic_Test_Innings_Count,Domestic_Test_Match_Count,Domestic_Test_Win_Rate,...,Domestic_Test_250_Rate,Domestic_Test_300_Rate,Domestic_T20_Duck_Rate,Domestic_T20_Start_Rate,Domestic_T20_50_Rate,Domestic_T20_100_Rate,Domestic_T20_150_Rate,Domestic_T20_200_Rate,Domestic_T20_250_Rate,Domestic_T20_300_Rate
0,21,"Bichel, Andrew",Right,23.250000,26,26,0.500000,54,33,0.515152,...,0.0,0.0,0.000000,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
1,22,"Bevan, Michael",Left,45.901961,20,20,0.450000,43,24,0.291667,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29,"Harvey, Ian",Right,19.785714,10,10,0.400000,22,13,0.538462,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,30,"Hayden, Matthew",Left,45.138211,8,8,0.375000,12,7,0.714286,...,0.0,0.0,0.000000,0.857143,0.142857,0.000000,0.0,0.0,0.0,0.0
4,32,"Hogg, Brad",Left,21.485714,15,15,0.266667,18,12,0.333333,...,0.0,0.0,0.266667,0.733333,0.000000,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2480058,"Labuschagne, Marnus",Right,37.866667,26,26,0.615385,98,54,0.462963,...,0.0,0.0,0.133333,0.866667,0.000000,0.000000,0.0,0.0,0.0,0.0
58,2960012,"Stoinis, Marcus",Right,33.540541,38,38,0.500000,95,52,0.403846,...,0.0,0.0,0.056338,0.732394,0.197183,0.014085,0.0,0.0,0.0,0.0
59,2960022,"Handscomb, Peter",Right,30.375000,58,58,0.431034,123,73,0.410959,...,0.0,0.0,0.035088,0.877193,0.070175,0.017544,0.0,0.0,0.0,0.0
60,3080014,"Head, Travis",Left,34.173913,27,27,0.296296,149,79,0.253165,...,0.0,0.0,0.020833,0.791667,0.166667,0.020833,0.0,0.0,0.0,0.0
61,3080018,"Zampa, Adam",Right,9.380952,29,29,0.275862,61,34,0.205882,...,0.0,0.0,0.172414,0.827586,0.000000,0.000000,0.0,0.0,0.0,0.0

## 7. Summarise Batting Position.

In this section, the batting position of each batter is summarised, including:

1. The average number of balls that have been bowled when each batter faces their first ball in a domestic One-Day innings.
2. The average score when each batter faces their first ball in a domestic One-Day innings.
3. The average number of wickets fallen when each batter faces their first ball in a domestic One-Day innings.
4. The average number of balls that have been bowled when each batter faces their first ball in a domestic Test innings.
5. The average score when each batter faces their first ball in a domestic Test innings.
6. The average number of wickets fallen when each batter faces their first ball in a domestic Test innings.
7. The average number of balls that have been bowled when each batter faces their first ball in a domestic T20 innings.
8. The average score when each batter faces their first ball in a domestic T20 innings.
9. The average number of wickets fallen when each batter faces their first ball in a domestic T20 innings.

In [8]:
# Extract batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Extract match IDs and match types for domestic games.
match_df = match_data[match_data["Series"].str.contains(
    "Domestic")][["Match_ID", "Match Type Id"]]

# Extract deliveries to relevant batters and add match details.
df = delivery_data[(delivery_data["Batter_ID"].isin(batter_ids))][
    ["Batter_ID", "Match_ID", "Innings", "Cum Inning Balls",
     "Cum Inning Score", "Cum Inning Wickets"]
]
df = pd.merge(left=match_df, right=df, on="Match_ID")


# Function to summarise the batting position of each batter.
def summarise_batting_position(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels
  first_ball_label = "Domestic_{}_Average_Entering_Ball".format(format_label)
  entering_score_label = "Domestic_{}_Average_Entering_Score".format(
      format_label)
  entering_wickets_label = "Domestic_{}_Average_Entering_Wicket".format(
      format_label)

  # Extract first ball of each batter.
  df = df.groupby(["Batter_ID", "Match_ID", "Innings"], as_index=False)[
      ["Cum Inning Balls", "Cum Inning Score", "Cum Inning Wickets"]].first()

  # Summarise batting positions.
  df = df.groupby(["Batter_ID"], as_index=False).agg(
      {"Cum Inning Balls": "mean", "Cum Inning Score": "mean", "Cum Inning Wickets": "median"})
  df.rename({"Cum Inning Balls": first_ball_label, "Cum Inning Score": entering_score_label,
            "Cum Inning Wickets": entering_wickets_label}, axis=1, inplace=True)

  # Merge summarised data into summary.
  summary = pd.merge(left=summary, right=df, on="Batter_ID", how="left")

  return summary


# Summarise One-Day batting position.
games_df = df[df["Match Type Id"] == 1]
summary_data = summarise_batting_position(games_df, summary_data, "One_Day")

# Summarise Test batting position.
games_df = df[df["Match Type Id"].isin([4, 5])]
summary_data = summarise_batting_position(games_df, summary_data, "Test")

# Summarise T20 batting position.
games_df = df[df["Match Type Id"] == 7]
summary_data = summarise_batting_position(games_df, summary_data, "T20")
summary_data

,Batter_ID,Name,Hand,International_One_Day_Batting_Average,Domestic_One_Day_Innings_Count,Domestic_One_Day_Match_Count,Domestic_One_Day_Win_Rate,Domestic_Test_Innings_Count,Domestic_Test_Match_Count,Domestic_Test_Win_Rate,...,Domestic_T20_300_Rate,Domestic_One_Day_Average_Entering_Ball,Domestic_One_Day_Average_Entering_Score,Domestic_One_Day_Average_Entering_Wicket,Domestic_Test_Average_Entering_Ball,Domestic_Test_Average_Entering_Score,Domestic_Test_Average_Entering_Wicket,Domestic_T20_Average_Entering_Ball,Domestic_T20_Average_Entering_Score,Domestic_T20_Average_Entering_Wicket
0,21,"Bichel, Andrew",Right,23.250000,26,26,0.500000,54,33,0.515152,...,0.0,204.423077,159.000000,6.0,405.037037,216.388889,6.0,87.750000,95.000000,6.5
1,22,"Bevan, Michael",Left,45.901961,20,20,0.450000,43,24,0.291667,...,NaN,76.750000,60.500000,2.0,51.837209,20.744186,1.0,NaN,NaN,NaN
2,29,"Harvey, Ian",Right,19.785714,10,10,0.400000,22,13,0.538462,...,NaN,113.800000,83.300000,2.0,339.590909,179.363636,5.0,NaN,NaN,NaN
3,30,"Hayden, Matthew",Left,45.138211,8,8,0.375000,12,7,0.714286,...,0.0,5.625000,4.000000,0.0,20.333333,8.583333,0.0,6.285714,5.857143,0.0
4,32,"Hogg, Brad",Left,21.485714,15,15,0.266667,18,12,0.333333,...,0.0,210.400000,162.133333,5.0,392.555556,215.333333,5.0,109.133333,126.133333,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2480058,"Labuschagne, Marnus",Right,37.866667,26,26,0.615385,98,54,0.462963,...,0.0,65.000000,58.692308,1.5,88.091837,41.377551,1.0,47.666667,63.000000,2.0
58,2960012,"Stoinis, Marcus",Right,33.540541,38,38,0.500000,95,52,0.403846,...,0.0,90.657895,82.394737,3.0,97.705263,46.021053,1.0,19.690141,23.633803,0.0
59,2960022,"Handscomb, Peter",Right,30.375000,58,58,0.431034,123,73,0.410959,...,0.0,119.344828,101.689655,3.0,156.593496,79.821138,2.0,48.052632,58.157895,2.0
60,3080014,"Head, Travis",Left,34.173913,27,27,0.296296,149,79,0.253165,...,0.0,27.296296,22.185185,1.0,135.557047,66.342282,2.0,31.520833,41.229167,1.0
61,3080018,"Zampa, Adam",Right,9.380952,29,29,0.275862,61,34,0.205882,...,0.0,234.689655,186.689655,7.0,406.245902,216.967213,7.0,103.103448,120.620690,7.0

## 8. Summarise Batting Style.

This section summarises each batters batting style, including:

1. The average number of balls faced per innings in domestic One-Day matches.
2. The percentage of false shots performed by a batter in domestic One-Day matches.
3. The average strike rate of a batter in domestic One-Day matches.
4. The average number of balls faced per innings in domestic Test matches.
5. The percentage of false shots performed by a batter in domestic Test matches.
6. The average strike rate of a batter in domestic Test matches.
7. The average number of balls faced per innings in domestic T20 matches.
8. The percentage of false shots performed by a batter in domestic T20 matches.
9. The average strike rate of a batter in domestic T20 matches.

In [9]:
# Extract batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Extract match IDs and match types for domestic games.
match_df = match_data[match_data["Series"].str.contains(
    "Domestic")][["Match_ID", "Match Type Id"]]

# Extract deliveries to relevant batters and add match details.
df = delivery_data[(delivery_data["Batter_ID"].isin(batter_ids))][[
    "Batter_ID", "Match_ID", "Innings", "Bat Score", "Inside Edge", "Outside Edge",
    "Play and Miss", "Hit on Pads", "Hit on Body", "Contact Error", "Opportunity"
]]
df = pd.merge(left=match_df, right=df, on="Match_ID")


# Function to summarise the number of balls a batter has faced.
def summarise_balls_per_innings(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels.
  ball_label = "Domestic_{}_Average_Ball_Count".format(format_label)
  innings_label = "Domestic_{}_Innings_Count".format(format_label)

  # Extract the total number of balls faced and innings played.
  balls = df[["Batter_ID", "Bat Score"]]
  balls = balls.groupby(["Batter_ID"], as_index=False)[
      "Bat Score"].size().rename({"size": ball_label}, axis=1)
  innings = summary[["Batter_ID", innings_label]]

  # Determine the average number of balls faced per innings.
  balls = pd.merge(left=balls, right=innings, on="Batter_ID", how="left")
  balls[ball_label] = np.where(
      balls[innings_label] < 1,
      balls[innings_label],
      balls[ball_label]/balls[innings_label]
  )
  balls = balls[["Batter_ID", ball_label]]

  # Merge average number of balls faced into summary data.
  summary = pd.merge(left=summary, right=balls, on="Batter_ID", how="left")

  return summary


# Function to summarise the false shots played by each batter.
def summarise_false_shots(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels
  false_shot_label = "Domestic_{}_False_Shot_Rate".format(format_label)

  # Extract balls that were false shots.
  false_shots = df[
      (df["Inside Edge"] == "Y") |
      (df["Outside Edge"] == "Y") |
      (df["Play and Miss"] == "Y") |
      (df["Hit on Pads"] == "Y") |
      (df["Hit on Body"] == "Y") |
      (df["Contact Error"] == "Y") |
      (df["Opportunity"] == "Y")
  ][["Batter_ID", "Bat Score"]]
  false_shots = false_shots.groupby(["Batter_ID"], as_index=False).size().rename({
      "size": false_shot_label}, axis=1)

  # Determine the number of balls faced by each batter.
  balls = df[["Batter_ID", "Bat Score"]]
  balls = balls.groupby(["Batter_ID"], as_index=False)[
      "Bat Score"].size().rename({"size": "Balls"}, axis=1)

  # Determine the percentage of false shots per batter.
  false_shots = pd.merge(left=balls, right=false_shots,
                         on="Batter_ID", how="left")
  false_shots[false_shot_label] = np.where(
      false_shots["Balls"] < 1,
      false_shots["Balls"],
      false_shots[false_shot_label]/false_shots["Balls"]
  )
  false_shots = false_shots[["Batter_ID", false_shot_label]]

  # Add the false shot data to the summary.
  summary = pd.merge(left=summary, right=false_shots,
                     on="Batter_ID", how="left")
  return summary


# Function to summarise the strike rate of each batter.
def summarise_strike_rate(df: pd.DataFrame, summary: pd.DataFrame, format_label: str):
  # Format labels
  strike_rate_label = "Domestic_{}_Strike_Rate".format(format_label)

  # Extract runs and balls.
  df = df[["Batter_ID", "Bat Score"]]
  df = df.groupby("Batter_ID", as_index=False).agg(
      {"Bat Score": ["sum", "count"]})
  df.columns = df.columns.to_flat_index()
  df.rename({df.columns[0]: "Batter_ID", df.columns[1]: strike_rate_label, df.columns[2]: "Balls"}, axis=1, inplace=True)

  # Summarise strike rate.
  df[strike_rate_label] = np.where(
      df["Balls"] < 1,
      df["Balls"],
      df[strike_rate_label]/df["Balls"]
  )
  df = df[["Batter_ID", strike_rate_label]]

  # Add strike rate to dataframe.
  summary = pd.merge(left=summary, right=df, on="Batter_ID", how="left")
  return summary


# Summarise One-Day batting style.
games_df = df[df["Match Type Id"] == 1]
summary_data = summarise_balls_per_innings(games_df, summary_data, "One_Day")
summary_data = summarise_false_shots(games_df, summary_data, "One_Day")
summary_data = summarise_strike_rate(games_df, summary_data, "One_Day")

# Summarise Test batting style.
games_df = df[df["Match Type Id"].isin([4, 5])]
summary_data = summarise_balls_per_innings(games_df, summary_data, "Test")
summary_data = summarise_false_shots(games_df, summary_data, "Test")
summary_data = summarise_strike_rate(games_df, summary_data, "Test")

# Summarise T20 batting style.
games_df = df[df["Match Type Id"] == 7]
summary_data = summarise_balls_per_innings(games_df, summary_data, "T20")
summary_data = summarise_false_shots(games_df, summary_data, "T20")
summary_data = summarise_strike_rate(games_df, summary_data, "T20")
summary_data

,Batter_ID,Name,Hand,International_One_Day_Batting_Average,Domestic_One_Day_Innings_Count,Domestic_One_Day_Match_Count,Domestic_One_Day_Win_Rate,Domestic_Test_Innings_Count,Domestic_Test_Match_Count,Domestic_Test_Win_Rate,...,Domestic_T20_Average_Entering_Wicket,Domestic_One_Day_Average_Ball_Count,Domestic_One_Day_False_Shot_Rate,Domestic_One_Day_Strike_Rate,Domestic_Test_Average_Ball_Count,Domestic_Test_False_Shot_Rate,Domestic_Test_Strike_Rate,Domestic_T20_Average_Ball_Count,Domestic_T20_False_Shot_Rate,Domestic_T20_Strike_Rate
0,21,"Bichel, Andrew",Right,23.250000,26,26,0.500000,54,33,0.515152,...,6.5,18.076923,0.157447,0.921277,30.222222,0.215686,0.629902,9.500000,0.184211,1.789474
1,22,"Bevan, Michael",Left,45.901961,20,20,0.450000,43,24,0.291667,...,NaN,62.850000,0.103421,0.692124,127.116279,0.101171,0.493780,NaN,NaN,NaN
2,29,"Harvey, Ian",Right,19.785714,10,10,0.400000,22,13,0.538462,...,NaN,24.600000,0.142276,0.841463,59.318182,0.123372,0.513410,NaN,NaN,NaN
3,30,"Hayden, Matthew",Left,45.138211,8,8,0.375000,12,7,0.714286,...,0.0,49.625000,0.141058,0.707809,80.583333,0.122027,0.610134,22.714286,0.245283,1.308176
4,32,"Hogg, Brad",Left,21.485714,15,15,0.266667,18,12,0.333333,...,8.0,26.666667,0.145000,0.755000,42.111111,0.117414,0.705805,4.400000,0.348485,0.939394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2480058,"Labuschagne, Marnus",Right,37.866667,26,26,0.615385,98,54,0.462963,...,2.0,46.576923,0.147812,0.908340,74.448980,0.121573,0.489720,16.200000,0.246914,1.123457
58,2960012,"Stoinis, Marcus",Right,33.540541,38,38,0.500000,95,52,0.403846,...,0.0,35.789474,0.155147,0.819118,59.357895,0.147012,0.526512,23.492958,0.185851,1.281175
59,2960022,"Handscomb, Peter",Right,30.375000,58,58,0.431034,123,73,0.410959,...,2.0,37.465517,0.152324,0.872526,69.910569,0.117804,0.533318,15.298246,0.230505,1.194954
60,3080014,"Head, Travis",Left,34.173913,27,27,0.296296,149,79,0.253165,...,1.0,32.481481,0.167617,1.099202,62.778523,0.146461,0.613107,21.312500,0.260997,1.318671
61,3080018,"Zampa, Adam",Right,9.380952,29,29,0.275862,61,34,0.205882,...,7.0,13.482759,0.304348,1.132992,26.737705,0.236052,0.721643,5.448276,0.468354,0.892405

## 9. Summarise Team Contribution.

Here, we summarise the contribution of each batter to their teams performance. This includes:

1. The average percent of runs each batter contributes to their teams total in domestic One-Day matches.
2. How often each batter is the highest scorer of their team (%) in domestic One-Day matches.
3. The average percent of runs each batter contributes to their teams total in domestic Test matches.
4. How often each batter is the highest scorer of their team (%) in domestic Test matches.
5. The average percent of runs each batter contributes to their teams total in domestic T20 matches.
6. How often each batter is the highest scorer of their team (%) in domestic T20 matches.

In [10]:
# Extract batter IDs.
batter_ids = summary_data["Batter_ID"].tolist()

# Extract match IDs and match types for domestic games.
match_df = match_data[match_data["Series"].str.contains(
    "Domestic")][["Match_ID", "Match Type Id"]]

# Extract deliveries to relevant batters and add match details.
df = delivery_data[["Batter_ID", "Match_ID", "Innings",
                    "Bat Score", "Team Batting Id", "Cum Inning Score"]]
df = pd.merge(left=match_df, right=df, on="Match_ID")

# Function to summarise the run contribution of each batter to their team.


def summarise_team_run_contribution(df: pd.DataFrame, summary: pd.DataFrame, format_label: str, batter_ids: list):
  # Format labels.
  high_score_label = "Domestic_{}_Team_Run_Contribution_Percent".format(
      format_label)

  # Extract the final score for each team in each match/innings.
  team_total = df.groupby(
      ["Match_ID", "Innings", "Team Batting Id"], as_index=False).last()
  team_total = team_total[["Match_ID", "Innings", "Team Batting Id", "Cum Inning Score"]].rename(
      {"Cum Inning Score": "Team_Total"}, axis=1)

  # Align the total number of runs scored in each game with each batter.
  team_total = pd.merge(left=df, right=team_total, on=[
                        "Match_ID", "Innings", "Team Batting Id"], how="left")
  team_total = team_total[team_total["Batter_ID"].isin(
      batter_ids)][["Batter_ID", "Match_ID", "Innings", "Team_Total"]]
  team_total.drop_duplicates(
      ["Batter_ID", "Match_ID", "Innings"], inplace=True)

  # Determine the total number of runs each batters teams scored.
  team_total = team_total[["Batter_ID", "Team_Total"]]
  team_total = team_total.groupby("Batter_ID", as_index=False).sum()

  # Extract the number of runs each batter has scored.
  total_runs = df[df["Batter_ID"].isin(batter_ids)]
  total_runs = total_runs.groupby("Batter_ID", as_index=False)[
      "Bat Score"].sum()
  total_runs.rename({"Bat Score": high_score_label}, axis=1, inplace=True)

  # Determine each batters contribution to their teams as a percentage.
  total_runs = pd.merge(left=total_runs, right=team_total,
                        on="Batter_ID", how="left")
  total_runs[high_score_label] = np.where(
      total_runs["Team_Total"] < 1,
      total_runs["Team_Total"],
      total_runs[high_score_label]/total_runs["Team_Total"]
  )
  total_runs = total_runs[["Batter_ID", high_score_label]]

  # Merge team run contribution into summary.
  summary = pd.merge(left=summary, right=total_runs,
                     on="Batter_ID", how="left")
  return summary

# Function to summarise how often a batter is the high scorer of their team.


def summarise_team_highest_scorer(df: pd.DataFrame, summary: pd.DataFrame, format_label: str, batter_ids: list):
  # Format labels
  high_score_label = "Domestic_{}_Team_High_Score_Percent".format(format_label)
  innings_label = "Domestic_{}_Innings_Count".format(format_label)

  # Extract the number of times each batter was the highest scorer.
  batter_ids = summary["Batter_ID"].tolist()
  highscore = df.groupby(["Match_ID", "Innings", "Team Batting Id",
                         "Batter_ID"], as_index=False)["Bat Score"].sum()
  idx = highscore.groupby(["Match_ID", "Innings", "Team Batting Id"])[
      "Bat Score"].transform(max) == highscore["Bat Score"]
  highscore = highscore[idx]
  highscore = highscore[highscore["Batter_ID"].isin(batter_ids)]
  highscore = highscore.groupby("Batter_ID", as_index=False).size().rename({
      "size": high_score_label}, axis=1)

  # Convert number of highest scores to percentage.
  innings = summary[["Batter_ID", innings_label]]
  innings = innings[innings[innings_label] > 0]
  highscore = pd.merge(left=innings, right=highscore,
                       on="Batter_ID", how="left")
  highscore[high_score_label] = np.where(
      highscore[innings_label] < 1,
      highscore[innings_label],
      highscore[high_score_label]/highscore[innings_label]
  )
  highscore = highscore[["Batter_ID", high_score_label]]
  highscore.fillna({high_score_label: 0}, inplace=True)

  # Add to summary.
  summary = pd.merge(left=summary, right=highscore, on="Batter_ID", how="left")
  return summary


# Summarise One-Day team contribution.
games_df = df[df["Match Type Id"] == 1]
summary_data = summarise_team_run_contribution(
    games_df, summary_data, "One_Day", batter_ids)
summary_data = summarise_team_highest_scorer(
    games_df, summary_data, "One_Day", batter_ids)

# Summarise Test team contribution.
games_df = df[df["Match Type Id"].isin([4, 5])]
summary_data = summarise_team_run_contribution(
    games_df, summary_data, "Test", batter_ids)
summary_data = summarise_team_highest_scorer(
    games_df, summary_data, "Test", batter_ids)

# Summarise T20 team contribution.
games_df = df[df["Match Type Id"] == 7]
summary_data = summarise_team_run_contribution(
    games_df, summary_data, "T20", batter_ids)
summary_data = summarise_team_highest_scorer(
    games_df, summary_data, "T20", batter_ids)
summary_data

,Batter_ID,Name,Hand,International_One_Day_Batting_Average,Domestic_One_Day_Innings_Count,Domestic_One_Day_Match_Count,Domestic_One_Day_Win_Rate,Domestic_Test_Innings_Count,Domestic_Test_Match_Count,Domestic_Test_Win_Rate,...,Domestic_Test_Strike_Rate,Domestic_T20_Average_Ball_Count,Domestic_T20_False_Shot_Rate,Domestic_T20_Strike_Rate,Domestic_One_Day_Team_Run_Contribution_Percent,Domestic_One_Day_Team_High_Score_Percent,Domestic_Test_Team_Run_Contribution_Percent,Domestic_Test_Team_High_Score_Percent,Domestic_T20_Team_Run_Contribution_Percent,Domestic_T20_Team_High_Score_Percent
0,21,"Bichel, Andrew",Right,23.250000,26,26,0.500000,54,33,0.515152,...,0.629902,9.500000,0.184211,1.789474,0.069782,0.038462,0.064488,0.018519,0.125230,0.250000
1,22,"Bevan, Michael",Left,45.901961,20,20,0.450000,43,24,0.291667,...,0.493780,NaN,NaN,NaN,0.190247,0.300000,0.214581,0.418605,NaN,NaN
2,29,"Harvey, Ian",Right,19.785714,10,10,0.400000,22,13,0.538462,...,0.513410,NaN,NaN,NaN,0.093034,0.100000,0.102134,0.136364,NaN,NaN
3,30,"Hayden, Matthew",Left,45.138211,8,8,0.375000,12,7,0.714286,...,0.610134,22.714286,0.245283,1.308176,0.157159,0.250000,0.146949,0.166667,0.179620,0.142857
4,32,"Hogg, Brad",Left,21.485714,15,15,0.266667,18,12,0.333333,...,0.705805,4.400000,0.348485,0.939394,0.087536,0.066667,0.098183,0.111111,0.029496,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2480058,"Labuschagne, Marnus",Right,37.866667,26,26,0.615385,98,54,0.462963,...,0.489720,16.200000,0.246914,1.123457,0.166844,0.230769,0.135495,0.173469,0.118131,0.066667
58,2960012,"Stoinis, Marcus",Right,33.540541,38,38,0.500000,95,52,0.403846,...,0.526512,23.492958,0.185851,1.281175,0.121722,0.105263,0.114083,0.115789,0.207960,0.239437
59,2960022,"Handscomb, Peter",Right,30.375000,58,58,0.431034,123,73,0.410959,...,0.533318,15.298246,0.230505,1.194954,0.135332,0.172414,0.133746,0.130081,0.122892,0.122807
60,3080014,"Head, Travis",Left,34.173913,27,27,0.296296,149,79,0.253165,...,0.613107,21.312500,0.260997,1.318671,0.148834,0.185185,0.144331,0.221477,0.178156,0.125000
61,3080018,"Zampa, Adam",Right,9.380952,29,29,0.275862,61,34,0.205882,...,0.721643,5.448276,0.468354,0.892405,0.063851,0.034483,0.070264,0.049180,0.034593,0.000000

## Write Summary to File.

With each batter summarised, we will write the summary dataframe to file.

In [11]:
summary_data.to_csv(DATA_PATH + "/Batter_Summary.txt", sep="\t", index=False)